version: '3'

services:

  apache:
    image: httpd:2.4
    container_name: "apache2-test"
    working_dir: "/var/www/html"
    ports:
      - "8880:80"
    volumes:
      - "./src:/var/www/html:rw"
      - "./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf"
    depends_on:
      - php
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.9

  nginx:
    build:
      context: docker/nginx
    container_name: "nginx-test"
    working_dir: "/var/www/html"
    ports:
      - "8888:80"
    volumes:
      - "./src:/var/www/html:rw"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - php
      - apache
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  php:
    build:
      context: docker/php
    container_name: "php-test"
    working_dir: "/var/www/html"
    volumes:
      - "./src:/var/www/html:rw"
    ports:
      - "9001:9000"
    depends_on:
      - db
      - redis
    restart: always
    links:
      - db
      - redis
    networks:
      app_net:
        ipv4_address: 172.16.238.11

  db:
    container_name: "mysql-test"
    image: bitnami/mysql:8.2.0-debian-11-r5
    ports:
      - "6033:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=test_db"
      - "MYSQL_USER=test_user"
      - "MYSQL_PASSWORD=e5%j~mkiXV}WQrfLa^rLnB7"
      - "MYSQL_ROOT_PASSWORD=e5%j~mkiXV}WQrfLa^rLnB7"
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    restart: always

  redis:
    image: redis:6.2-alpine
    container_name: "redis-test"
    ports:
      - "6379:6379"
    command: "redis-server --save 20 1 --loglevel warning --requirepass McamLFxDKhSH"
    volumes:
      - "./data/redis:/data:rw"
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.13

volumes:
  db:
    driver: local
  redis:
    driver: local
  data:
    driver: local

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
